### PR TITLE
code to clear error on one herkulex motor and move angle

### PR DESCRIPTION
**Pull request by nixonjosephb**
This code allows single herkulex motor to be moved to a specified angle and tested from the cardboard test kit using Arduino mega. This code will clear pending errors from the motor to get it to run again, this will only clear the error once in setup() so any compounding errors will not be cleared.

### CODE REVIEW

**Comment by Skylerwiernik** [comment]
Can this be cleaned up a bit before we merge? Mainly just getting rid of those lines that are commented out

**Comment by nixonjosephb** [comment]
yes, I can definitely clean this up, this was just mainly me learning how to upload to git. Will remove commented lines

**Review by tha-wpi — APPROVED** [review]
Thank you for creating and sharing this working code example. Clearing servo error codes should refer to this sample.

**Comment by tha-wpi** [comment]
> Can this be cleaned up a bit before we merge? Mainly just getting rid of those lines that are commented out

Quality improvement shouldn't hold up checkins to test/. These are coding efforts currently that may not be backed up anywhere. Right now top priority is get all working code into test/ structure.

After collecting all working test/ code the CS majors will lead the implementation of the platform integration phase. There we'll have more of a focus on professional coding.

**Comment by tha-wpi** [comment]
Merging this now to get error-clearing motor verification code in test/ to others.

**Pull request merged**
